name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Change directory to "back-end"
        run: cd back-end

      - name: Debug - List Directory Contents
        run: |
          pwd
          ls -l

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip

      - name: Install Python dependencies
        run:
          pip install -r ./back-end/requirements-dev.txt

      - name: Test with pytest
        run: python -m pytest ./tests