name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: List directory contents
        run: ls -l

      - name: Find "back-end" directory
        run: |
          find . -type d -name "back-end"
          cd /home/runner/work/CxOCP/CxOCP/back-end
          pwd

      - name: Debug - List Directory Contents
        run: |
          pwd
          ls -l

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip

      - name: Install Python dependencies
        run:
          pip install -r /back-end/requirements-dev.txt

      - name: Test with pytest
        run: python -m pytest ./tests