name: CI/CD

on:
  push:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r back-end/requirements-dev.txt

      - name: Test with pytest
        run: python -m pytest back-end/tests

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/back-end-image:latest -f back-end/Dockerfile back-end
  Register:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Push Docker image
        run: |
          docker login ${{ secrets.AZURE_CONTAINERS_SERVER }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}
          docker push ${{ secrets.AZURE_CONTAINERS_SERVER }}/back-end-image:latest