name: CI-CD FE

on:
  push:
    paths:
      - 'front-end/**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Test with something
        run: echo "Learn to test the front-end boy!"

  Build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Login Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build front-end
        run: docker build -t ${{ secrets.CONTAINER_REGISTRY }}/front-end-image:${{ github.sha }} -f front-end/Dockerfile front-end

      - name: Push front-end
        run: docker push ${{ secrets.CONTAINER_REGISTRY }}/front-end-image:${{ github.sha }}